### ISSUE TITLE
Hledání produktů

### ISSUE THREAD

**Issue by bisof** [Webinators/Konfigurator-zahradnich-traktoru#20]
nyní není funkční vyhledávání respektive nic nevypisuje i když to zadávám přesně podle produktu

**Comment by bouchn01** [comment]
Je to neuvěřitelné, ale když jsem to testoval já, tak mi to normálně funguje. Zkuš prohlížeč jiný.

**Comment by bisof** [comment]
Nevím čím to bylo ale už mi to funguje bez problémů asi slabá wifi síť
